// Application/DTOs/SmartReorder/CreateSmartReorderDto.cs
namespace Application.DTOs.SmartReorder
{
    public class CreateSmartReorderDto
    {
        public int ItemId { get; set; }
        public int GodownId { get; set; }
        public int SupplierId { get; set; }
        public DateTime ReorderDate { get; set; }
        public decimal CurrentStock { get; set; }
        public decimal ReorderPoint { get; set; }
        public decimal ReorderQuantity { get; set; }
        public decimal EconomicOrderQuantity { get; set; }
        public decimal SafetyStock { get; set; }
        public decimal LeadTimeDemand { get; set; }
        public decimal AverageLeadTime { get; set; }
        public string ReorderReason { get; set; } = string.Empty;
        public decimal EstimatedCost { get; set; }
        public DateTime? ExpectedDelivery { get; set; }
        public bool IsAutoGenerated { get; set; } = true;
        public decimal ConfidenceScore { get; set; } = 1.0m;
        public string? Notes { get; set; }
    }
}