// Application/DTOs/SmartReorder/SmartReorderDto.cs
using Application.DTOs.Common;

namespace Application.DTOs.SmartReorder
{
    public class SmartReorderDto : BaseDto
    {
        public int ItemId { get; set; }
        public string? ItemName { get; set; }
        public int GodownId { get; set; }
        public string? GodownName { get; set; }
        public int SupplierId { get; set; }
        public string? SupplierName { get; set; }
        public DateTime ReorderDate { get; set; }
        public decimal CurrentStock { get; set; }
        public decimal ReorderPoint { get; set; }
        public decimal ReorderQuantity { get; set; }
        public decimal EconomicOrderQuantity { get; set; }
        public decimal SafetyStock { get; set; }
        public decimal LeadTimeDemand { get; set; }
        public decimal AverageLeadTime { get; set; }
        public string ReorderReason { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public decimal EstimatedCost { get; set; }
        public DateTime? ExpectedDelivery { get; set; }
        public DateTime? ActualDelivery { get; set; }
        public bool IsAutoGenerated { get; set; }
        public decimal ConfidenceScore { get; set; }
        public string? Notes { get; set; }
    }
}