// Application/Contracts/ISmartReorderRepository.cs
using Application.DTOs.Common;
using Domain.Models;
using System.Threading;
using System.Threading.Tasks;

namespace Application.Contracts
{
    public interface ISmartReorderRepository : IGenericRepository<SmartReorder>
    {
        Task<PagedResult<SmartReorder>> GetPagedReordersAsync(int pageNumber, int pageSize, string? status, string? reorderReason, CancellationToken cancellationToken);
        Task<IReadOnlyList<SmartReorder>> GetPendingReordersAsync(CancellationToken cancellationToken);
        Task<IReadOnlyList<SmartReorder>> GetReordersByItemAsync(int itemId, CancellationToken cancellationToken);
        Task<IReadOnlyList<SmartReorder>> GetAutoGeneratedReordersAsync(CancellationToken cancellationToken);
        Task<SmartReorder?> GetLatestReorderByItemAsync(int itemId, int godownId, CancellationToken cancellationToken);
        Task UpdateStatusAsync(int reorderId, string status, CancellationToken cancellationToken);
        Task<IReadOnlyList<SmartReorder>> GetOverdueReordersAsync(CancellationToken cancellationToken);
        Task AddAsync(SmartReorder smartReorder);
    }
}